# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev1+ge57e271.d20250129'
__version_tuple__ = version_tuple = (0, 1, 'dev1', 'ge57e271.d20250129')
